#!/bin/bash
#
# SessionStart hook — project setup for Claude Code cloud sessions.
#
# Registered in .claude/settings.json. Runs after Claude Code launches, on every cloud
# session including resumed ones, and does the three things the environment snapshot
# cannot do for us:
#
#   1. `npm ci`, because node_modules is not in the repository and package-lock.json moves;
#   2. exports CHROME_PATH, because the Chrome directory name carries its version;
#   3. writes .env.local, because src/lib/supabase.js builds its client at module scope and
#      shared/supabase/client.js throws when either VITE_SUPABASE_* value is missing — a
#      bundle built without them crashes on load, so `npm run build` fails before the
#      verifiers get to measure anything. Same reason .github/workflows/ci.yml sets them.
#
# It exits immediately outside the cloud. CLAUDE_CODE_REMOTE is `true` only on a session
# VM, never on a developer's machine, so a local `claude` in this repo runs nothing here
# and your working tree is left exactly as it was.
#
# Like the setup script it must exit 0 — a failing SessionStart hook is reported to Claude
# rather than silently ignored, and a session that cannot npm-install is still a session
# worth having for reading code.
#
set -u

[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0
say() { echo "[session-start] $*"; }

# ── Dependencies ──────────────────────────────────────────────────────────────────────
#
# Skipped when node_modules is already populated and no newer lockfile has landed, because
# this hook runs on every resume and `npm ci` deletes and rebuilds node_modules every time
# it is called. `npm ci` rather than `npm install` so the tree matches package-lock.json
# exactly, which is what CI installs.
if [ ! -d node_modules ] || [ package-lock.json -nt node_modules ]; then
  say "installing dependencies (npm ci)"
  npm ci --no-audit --no-fund >/dev/null 2>&1 || {
    say "npm ci failed, falling back to npm install"
    npm install --no-audit --no-fund >/dev/null 2>&1 || say "WARNING: dependency install failed"
  }
else
  say "dependencies already present"
fi

# ── CHROME_PATH ───────────────────────────────────────────────────────────────────────
#
# scripts/verify-*.mjs each read process.env.CHROME_PATH and fall back to a Windows path,
# which is the right default on the machine this project is developed on and useless here.
# scripts/cloud-setup.sh recorded the resolved binary; writing to $CLAUDE_ENV_FILE is what
# makes the value visible to the Bash commands Claude runs afterwards.
if [ -f /opt/chrome/CHROME_PATH ] && [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  echo "CHROME_PATH=$(cat /opt/chrome/CHROME_PATH)" >> "$CLAUDE_ENV_FILE"
  say "CHROME_PATH exported - the verify:* suites can run"
elif [ ! -f /opt/chrome/CHROME_PATH ]; then
  say "no Chrome on this image - verify:* will not run (see scripts/cloud-setup.sh)"
fi

# ── .env.local ────────────────────────────────────────────────────────────────────────
#
# Written from the environment variables configured on the cloud environment, and only
# when it does not already exist, so a session that was given a file some other way keeps
# it. Both values are public by design: the publishable key ships to every visitor's
# browser and grants nothing on its own — Row Level Security is what protects the data.
# That is why they are safe in an environment configuration and SUPABASE_SECRET_KEY and
# SUPABASE_DB_PASSWORD are not; see .env.cloud.example.
if [ ! -f .env.local ]; then
  if [ -n "${VITE_SUPABASE_URL:-}" ] && [ -n "${VITE_SUPABASE_PUBLISHABLE_KEY:-}" ]; then
    {
      echo "# Generated by scripts/install_pkgs.sh from the cloud environment variables."
      echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL"
      echo "VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY"
    } > .env.local
    say ".env.local written - npm run build and npm run dev are ready"
  else
    say "WARNING: VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY unset"
    say "         npm test works; npm run build and the verify:* suites will fail"
    say "         set them at claude.ai/code -> environment -> Environment variables"
  fi
fi

exit 0
